# Generated by Django 4.1.7 on 2023-04-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ABCApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=5000)),
                ("email", models.EmailField(max_length=5000)),
                ("message", models.TextField(max_length=5000)),
            ],
        ),
    ]
